apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: mongodb
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: {{ .Values.statefulset.replicas }} # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mongodb
        project: roboshop
        tier: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: dockerdevops1994/mongodb:{{ .Values.statefulset.version }}
        volumeMounts:
        - name: persistent-storage
          mountPath: /data/db
      nodeSelector:
        zone: 1f
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 2Gi




















